### ISSUE TITLE
Verify that /wp/plugins and /wp/themes links work

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/jsdelivr-wordpress#11]
http://plugins.svn.wordpress.org/wp-slick-slider-and-image-carousel/tags/

There is no tag for the latest 1.5.1 so the generated URLs such as https://cdn.jsdelivr.net/wp/plugins/wp-slick-slider-and-image-carousel/tags/1.5.1/assets/css/slick.css result in 404. The generated links should be checked first and only stored in the DB if they work (the best way is probably comparing contents with the local file).

**Comment by jimaek** [comment]
@MartinKolarik Do you know a very fast method to do that? Because sending 30+ HTTP requests to verify the existence could A. trigger anti-abuse in shared hosting B. slow down the website A LOT

**Comment by MartinKolarik** [comment]
We are already sending that many requests to our API but it's a one time thing (this too). Unless there's no match, in which case it's retried in next analyze, which is in 5 minutes I think. We might want to do something with that.

My suggestion: for automatic analyze (cron) don't analyze the same file more than once per 24 hours (or even 48). If started manually, always analyze all files.

**Comment by jimaek** [comment]
My worry here is that the cron by default runs in "fake" mode. Its triggered by every user request to the website and if the time is right it executes everything in there.
So if our API or our CDN are slow our cron would block the loading of the site until it checked all the files for validity and downloaded all API data.
Seems like a potential issue for me and users with big sites.

**Comment by MartinKolarik** [comment]
I know about that although I'm not sure if it actually blocks the request (it is possible to implement it in a non-blocking way). Anyway that's why I suggested using a larger interval.

**Comment by jimaek** [comment]
https://github.com/jsdelivr/jsdelivr-wordpress/issues/14

**Comment by HesyRa** [comment]
@MartinKolarik what u thing about checking allowing also 301 and 302 codes, do we need them to be allowed ?
