### ISSUE TITLE
Use an async cron

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr-wordpress#14]
http://qnimate.com/how-wordpress-executes-async-cron-without-effecting-page-load-time/

**Comment by MartinKolarik** [comment]
Based on the article this is how it works already.

**Comment by jimaek** [comment]
Is it? I dont see any async code anywhere.

**Comment by MartinKolarik** [comment]
It should be handled by WP.

**Comment by jimaek** [comment]
I believe HesyRa in his testing said that cron blocks the site as well. So are you sure that its async by default and we don't need to do anything?

**Comment by MartinKolarik** [comment]
That's what the article says and I would expect WP devs are smart enough to make it that way but I'll check.

**Comment by MartinKolarik** [comment]
> The HTTP request to this file will not slow down the visitor who happens to visit when the cron job is needed to run.

https://github.com/WordPress/WordPress/blob/master/wp-cron.php
