### ISSUE TITLE
Do we need to hardcode the version?

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr-wordpress#18]
https://github.com/jsdelivr/jsdelivr-wordpress/blob/1061a803b0e28c38763a47bc27bedddcd1e898ff/jsdelivr-cdn.php#L40

**Comment by MartinKolarik** [comment]
I would prefer `1.0.0` though.

**Comment by jimaek** [comment]
I thought wordpress pulled it from readme.txt. 
So if its not needed in the code we should remove it

**Comment by jimaek** [comment]
I am pretty sure if WP reads it from the readme it will exist somewhere as a variable without needing for us to register our own version.

**Comment by MartinKolarik** [comment]
It would be pretty stupid if they really read it from the readme.txt at every request but @HesyRa please check.

**Comment by jimaek** [comment]
>*  Change the version number in the header comment of the main PHP file to the new version number (in the trunk folder).
>*  Change the version number in the 'Stable tag' field of the readme.txt file (in the trunk folder).
>

So according to that we only need the version in the comments and readme. I dont think this is needed at all 
```
define( 'JSDELIVRCDN_VERSION', '1.0' );
define( 'JSDELIVRCDN_MINIMUM_WP_VERSION', '4.0' );
```

**Comment by jimaek** [comment]
ok, then lets remove the version and create a separate task to check WP versions for min supported

**Comment by HesyRa** [comment]
@jimaek acording to https://github.com/jsdelivr/jsdelivr-wordpress/issues/15 this issue we will send plugin version to all request to API. Yes, we can get version from comment at main file, but I think much better just define variable as it is now.

**Comment by MartinKolarik** [comment]
@HesyRa it also says "This function only works in the admin area". Not sure if cron counts as admin area but if yes then we could probably use it. It's very ineffective but in this case that doesn't matter and it'll be easier to maintain this way.
