### ISSUE TITLE
Changes don't take effect immediatelly

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/jsdelivr-wordpress#21]
After running analyze and enabling everything, the files are still being loaded from original URLs for maybe 10 minutes. Later the jsDelivr URLs are used. I don't have any special caching plugin installed. @HesyRa do you know what causes this delay? Can we do something about it or just document it?

**Comment by HesyRa** [comment]
@MartinKolarik Okay, I will need to do even more tests and investigations.

**Comment by MartinKolarik** [comment]
In case this doesn't happen with all files, it happened for `wp-content/plugins/fruitful-shortcodes/includes/shortcodes/css/font-awesome.min.css` (there were more but I remember this one).

**Comment by HesyRa** [comment]
@MartinKolarik Tried few times at https://github.com/jsdelivr/jsdelivr-wordpress/pull/22 everything is worked correctly. The only feature we need to document (for now) is capturing sources, needed few page reloads to capture all source. After 'analyze' action filled urls are immidiatly replaced with jsdelivr. 
Let's check
