### ISSUE TITLE
Replacing HTML scanning for smart enqueue support

### ISSUE THREAD

**Issue by hubdotcom** [jsdelivr/jsdelivr-wordpress#5]
HTML scanning is memory hungry and slow. Better to update this to use the native WP functionality? (or at least provide the option to choose)

A good example is this plugin:
https://wordpress.org/support/plugin/versions

The advanced mode uses the following hooks to perform in place manipulations:

```
                    add_action( 'wp_print_scripts', array( __CLASS__, 'handle_enqueued_scripts' ), 999);
                    add_action( 'wp_print_styles', array( __CLASS__, 'handle_enqueued_styles' ), 999);
```

And a HTML scanning is as follows:

```
                 add_action( 'plugins_loaded', array( __CLASS__, 'start_html_buffer' ) );
                    add_action( 'wp_footer', array( __CLASS__, 'stop_html_buffer' ), 999 );
```

**Comment by jimaek** [comment]
Our plugin was written by a freelancer and at this moment I cant afford to hire an other freelancer to update the plugin. If you are interested to improve it then feel free to do so :)

**Comment by hubdotcom** [comment]
I understand. This should be high priority for wider adoption of the plugin since it seems many people are having the same issue based on the support requests. It would also be inline with jsDelivr philosophy since HTML output buffering is a slow way of processing the files

**Comment by jimaek** [comment]
If you want you are welcomed to try to update it. But unfortunately I cant dedicate resources to this project right now.

**Comment by MartinKolarik** [comment]
This has been implemented.
