### ISSUE TITLE
Didn't catch css

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr-wordpress#7]
https://dl.dropboxusercontent.com/s/qlvxc7117kxmqx0/chrome_2018-08-20_20-52-27.png

```

woocommerce-general | 3.4.4 | //142.93.239.210/wp-content/plugins/woocommerce/assets/css/twenty-seventeen.css



```

**Comment by MartinKolarik** [comment]
@HesyRa my guess is php doesn't understand `//` and you'll need to prepend `http:` in this case.

**Comment by HesyRa** [comment]
![image](https://user-images.githubusercontent.com/14232439/45172913-609dad80-b20f-11e8-9fbe-5871d218d55a.png)
@MartinKolarik I think trouble is connected to IP address as url. Also can you please recheck it after https://github.com/jsdelivr/jsdelivr-wordpress/pull/22 merged ? Thnx.

**Comment by HesyRa** [comment]
@MartinKolarik Can you please take a loot at this trouble? (Can't repeat this localy).  Also would be cool to get data from our plugin for this trouble (screen or data from stored DB options).
