### ISSUE TITLE
Don't show not found files in regular mode

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr-wordpress#8]
For example https://dl.dropboxusercontent.com/s/yi1tu3tgyjd85j5/chrome_2018-08-20_20-54-00.png
The user does not need to know about this I think. There is nothing he can do

**Comment by HesyRa** [comment]
@MartinKolarik If we do this, there are also no reason to show 'analyze' button because user without advanced mode will not see any row until they filled with jsdelivr url (after cron worked). What do you thing about?

**Comment by MartinKolarik** [comment]
Indeed. I think we should keep showing those files in regular mode then because this would be a problem:
 1. user installs the plugin and wants to see how many files it found
 2. visits plugin options 
 3. it's empty

**Comment by HesyRa** [comment]
@jimaek Should we close this issue or wait design first?

**Comment by jimaek** [comment]
That's not a design task but a logic one. 
It looks like you both agree to show not found files.
Let's keep it as is then
